{% set name = "pyubx2" %}
{% set version = "1.2.57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyubx2-{{ version }}.tar.gz
  sha256: d845d7869210eb6dc70f3998500870af3a2209c310780872c282b610a1f7d6af
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pynmeagps >=1.0.50
    - pyrtcm >=1.1.9

test:
  imports:
    - pyubx2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pyubx2
  description: Python library for parsing and generating u-blox UBX GNSS protocol messages.
  summary: UBX protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyubx2
  dev_url: https://github.com/semuconsulting/pyubx2

extra:
  recipe-maintainers:
    - semuadmin
