{% set name = "pyubx2" %}
{% set version = "1.2.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyubx2-{{ version }}.tar.gz
  sha256: aa8062468f8b93b83fed8656c62bc369940588031b7d7d31127331a18ae88a4b
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - pynmeagps >=1.0.39
    - pyrtcm >=1.1.1

test:
  imports:
    - pyubx2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyubx2
  description: Python library for parsing and generating u-blox UBX GNSS protocol messages.
  summary: UBX protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyubx2
  dev_url: https://github.com/semuconsulting/pyubx2

extra:
  recipe-maintainers:
    - semuadmin
