{% set name = "pyubx2" %}
{% set version = "1.2.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyubx2-{{ version }}.tar.gz
  sha256: baed6e4920c0166c43c70bea1bb558669bbf8de019e9c7c5114b5e0fc0de5a16
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - pynmeagps >=1.0.39
    - pyrtcm >=1.1.1

test:
  imports:
    - pyubx2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semuconsulting/pyubx2
  description: Python library for parsing and generating u-blox UBX GNSS protocol messages.
  summary: UBX protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyubx2
  dev_url: https://github.com/semuconsulting/pyubx2

extra:
  recipe-maintainers:
    - semuadmin
